### ISSUE TITLE
ES version = 5.5.3,repository-cos-5.5.3.zip，elasticsearch-repository-oss-5.5.3.zip

### ISSUE THREAD

**Issue by Guilty8908** [tencentyun/elasticsearch-repository-cos#15]
阿里云的 elasticsearch 的OSS插件 elasticsearch-repository-oss ，跟  腾讯云的 elasticsearch 的COS 插件 repository-cos  是不是 不能共存呀？ 共存的话 就报错。

**Comment by Ethan-Zhang** [comment]
可以贴一下具体报错信息看看，还有linux，jdk，es的版本

**Comment by Guilty8908** [comment]
通过docker启动的ES 5.5.3
[2022-03-29T09:08:53,537][INFO ][o.e.n.Node               ] [] initializing ...
[2022-03-29T09:08:53,597][INFO ][o.e.e.NodeEnvironment    ] [QOpa8bb] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/vda1)]], net usable_space [51.7gb], net total_space [58.9gb], spins? [possibly], types [ext4]
[2022-03-29T09:08:53,598][INFO ][o.e.e.NodeEnvironment    ] [QOpa8bb] heap size [1.9gb], compressed ordinary object pointers [true]
[2022-03-29T09:08:53,599][INFO ][o.e.n.Node               ] node name [QOpa8bb] derived from node ID [QOpa8bbmRpKPOe_sljfVSw]; set [node.name] to override
[2022-03-29T09:08:53,599][INFO ][o.e.n.Node               ] version[5.5.3], pid[1], build[9305a5e/2017-09-07T15:56:59.599Z], OS[Linux/4.15.0-159-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_141/25.141-b16]
[2022-03-29T09:08:53,600][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Xms2g, -Xmx2g, -Des.path.home=/usr/share/elasticsearch]
[2022-03-29T09:08:55,607][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [aggs-matrix-stats]
[2022-03-29T09:08:55,607][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [ingest-common]
[2022-03-29T09:08:55,607][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [lang-expression]
[2022-03-29T09:08:55,607][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [lang-groovy]
[2022-03-29T09:08:55,607][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [lang-mustache]
[2022-03-29T09:08:55,608][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [lang-painless]
[2022-03-29T09:08:55,608][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [parent-join]
[2022-03-29T09:08:55,608][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [percolator]
[2022-03-29T09:08:55,608][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [reindex]
[2022-03-29T09:08:55,608][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [transport-netty3]
[2022-03-29T09:08:55,608][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded module [transport-netty4]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [analysis-icu]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [analysis-ik]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [analysis-kuromoji]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [analysis-pinyin]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [analysis-smartcn]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [elasticsearch-repository-oss]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [ingest-attachment]
[2022-03-29T09:08:55,609][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [ingest-geoip]
[2022-03-29T09:08:55,610][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [ingest-user-agent]
[2022-03-29T09:08:55,610][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [repository-cos]
[2022-03-29T09:08:55,610][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [repository-s3]
[2022-03-29T09:08:55,610][INFO ][o.e.p.PluginsService     ] [QOpa8bb] loaded plugin [x-pack]
[2022-03-29T09:08:56,459][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: Cannot register setting [access_key_id] twice
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.3.jar:5.5.3]
Caused by: java.lang.IllegalArgumentException: Cannot register setting [access_key_id] twice
	at org.elasticsearch.common.settings.SettingsModule.registerSetting(SettingsModule.java:168) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:74) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.3.jar:5.5.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.3.jar:5.5.3]
	... 6 more
